version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install -r lambdarequirements.txt -t ../python
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - echo "Zipping python libs..."
      - zip -r9 python.zip python
      - echo $(ls)
  post_build:
    commands:
      - echo "Uploading deployment package to s3..."
      - aws s3 sync . s3://data-manager-s3-bucket --delete
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name data-manager --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
